# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
 
pool:
  name: pool1
 
steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
 
- script: |
    echo "Simulating deployment..."
    mkdir deployed
    copy target\*.jar deployed\
    echo "Deployment successful!"
  displayName: 'Simulate Deployment'
 
- script: |
    echo "Running the JAR file..."
    java -jar deployed\*.jar
  displayName: 'Run Application'
